// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtHr_qEWvGZygQXKNwdIAhPa58ILTaAIw',
    appId: '1:241715939585:web:553f3aa9f6f9ce32f97300',
    messagingSenderId: '241715939585',
    projectId: 'diyar-app',
    authDomain: 'diyar-app.firebaseapp.com',
    storageBucket: 'diyar-app.firebasestorage.app',
    measurementId: 'G-8NZKP5M9MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXbT7RW9e0yiO2lDGm712m6ddek25bWL0',
    appId: '1:241715939585:android:b06cc1e6c7bfb8d9f97300',
    messagingSenderId: '241715939585',
    projectId: 'diyar-app',
    storageBucket: 'diyar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOzHMP_RhVZqw0SSiVeFVtkP5IAwjSSpY',
    appId: '1:241715939585:ios:82d74337ac807392f97300',
    messagingSenderId: '241715939585',
    projectId: 'diyar-app',
    storageBucket: 'diyar-app.firebasestorage.app',
    iosBundleId: 'com.uis.diyariosapp',
  );
}
